services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    pimcore.fixtures.loader:
        class: Instride\PimcoreFixturesBundle\Loader\ObjectFixturesLoader
        public: true
